### ISSUE TITLE
need to import IgfsUtils in few classes

### ISSUE THREAD

**Issue by pramodwerea** [EchoWine/unicredit#3]
e.g. in IgfsCgiNIT.php, we are using IgfsUtils class but it is not imported with **use**. Lets update code by adding use Railken\Unicredit\IGFS_CG_API\IgfsUtils also. Please check in other files also there is some class not imported.

**Comment by railken** [comment]
Hi again,

The IGFS_CG_API is the "Api Pack" provided by Unicredit, i have added namespaces only for the classes that i needed, if you need others classes or want to make it complete feel free to submit a pr. Otherwise please list here all the classes that you need.

**Comment by pramodwerea** [comment]
Okay, if needed I will ask for the pull request later!

**Comment by pramodrauniyar** [comment]
Hi, I have updated few files e.g. BaseIgfsCgTran.php  and IgfsCgCredit.php where I imported IgfsUtils.
@pramodwerea  is my office account so I made a pull request with my own git account. Waiting for you to accept git pull request. Thanks.

**Comment by railken** [comment]
Fixed the remaining namespaces with https://github.com/railken/Unicredit/commit/fefe360384e8a7d4ee33c8c70acdd5de720560c5
