### ISSUE TITLE
composer code base is not updated yet

### ISSUE THREAD

**Issue by pramodrauniyar** [EchoWine/unicredit#7]
@railken ,  although latest changes are on the master branch, while installing via composer it is not updated. Could you update the composer codebase?  I tried to install via composer and still getting old code. 
[https://packagist.org/packages/railken/unicredit](url)

Thanks!

**Comment by railken** [comment]
I will release a new version this evening.

If you need this right now: in your composer.json set the version to "dev-master" instead of "1.0.0"

**Comment by pramodrauniyar** [comment]
even dev-master is pointing to the commit : 7ca64f414124b27cca9c8b1e9ce10998b97c2d75. Anyway, wait for the release. It will be nice to have ASAP. Thanks!

**Comment by railken** [comment]
oh, i see. 

dev-master is now updated

**Comment by pramodrauniyar** [comment]
Great! thanks!

**Comment by railken** [comment]
Released v1.0.1
