### ISSUE TITLE
Unicredit production api url

### ISSUE THREAD

**Issue by rezamarandi** [EchoWine/unicredit#9]
Hi 
Actually i search alot for Unicredits API production url ..
Can you help me , how to find it ?

**Comment by railken** [comment]
Hi, sorry for the delay

@rezamarandi Have you already tried reading this? https://pagamenti.unicredit.it/UNI_CG_BRANDING/UNI/doc/api_manual_EN.pdf

Backoffice url: https://pagamenti.unicredito.it/backoffice/login.jsp
